FROM quay.io/buildah/stable:v1.23.0

USER build
WORKDIR /home/build
RUN export STORAGE_DRIVER=vfs
# Add plugin binary
ADD release/linux/amd64/drone-docker /bin/
ADD buildah-binaries/bin/buildah /bin/
ADD buildah-binaries/bin/imgtype /bin/
ADD buildah-binaries/bin/copy /bin/
ENTRYPOINT ["/bin/drone-docker"]