FROM quay.io/buildah/stable:v1.43.1

USER build
WORKDIR /home/build
ENV STORAGE_DRIVER=vfs

# Add plugin binaries
ADD release/linux/amd64/drone-docker /bin/
ADD release/linux/amd64/drone-heroku /bin/
ENTRYPOINT ["/bin/drone-heroku"]
